name: filebrowser
version: 1.0.1
slug: filebrowser
description: Enable filebrowser to 
url: https://github.com/pabloalcantara/hassio-addons/filebrowser

startup: once
boot: manual
init: false
startup: services

arch:
- aarch64
- amd64
- armhf
- armv7
- i386

map:
- backup:rw
- config:rw
- ssl:rw
- addons:rw
- share:rw
- media:rw

options: 
  username: admin
  password: admin
  hosts_allow: "*"

ports:
  9568/tcp: 80 

schema:
  username: str
  password: str
  hosts_allow: str
