name: filebrowser
version: 1.0.6
slug: filebrowser
description: Enable filebrowser
url: https://github.com/pabloalcantara/hassio-addons/filebrowser

startup: once
boot: manual
init: false
startup: application

arch:
- aarch64
- amd64
- armhf
- armv7
- i386

map:
- backup:rw
- config:rw
- ssl:rw
- addons:rw
- share:rw
- media:rw

ports_description: {"9568/tcp": "Filebrowser Web Interface"},
ports:
  9568/tcp: null
  
ingress: true
ingress_port: 9568
#ingress_stream: true  

webui: http://[HOST]:[PORT:9568]
