name: filebrowser
version: 1.0.7
slug: filebrowser
description: Enable filebrowser
url: https://github.com/pabloalcantara/hassio-addons/filebrowser

startup: once
boot: manual
init: false
startup: application

arch:
- aarch64
- amd64
- armhf
- armv7
- i386

map:
- backup:rw
- config:rw
- ssl:rw
- addons:rw
- share:rw
- media:rw

host_network: true
ports:
  80/tcp: 9568
ports_description:
  80/tcp: Filebrowser Web Interface
  
ingress: true
ingress_port: 0
ingress_stream: true  

webui: http://[HOST]:[PORT:9568]
