name: RsyncD
version: 1.2.2
slug: rsyncd
description: Enable RsyncD with module Name rsyncd
url: https://github.com/pabloalcantara/hassio-addons/rsyncd

startup: once
boot: manual
init: false
startup: services

arch:
- aarch64
- amd64
- armhf
- armv7
- i386

map:
- backup:rw
- config:rw
- ssl:rw
- addons:rw
- share:rw
- media:rw

options: 
  username: admin
  password: admin
  hosts_allow: "*"

ports:
  14678/tcp: 14678
watchdog: tcp://[HOST]:[PORT:14678]

schema:
  username: str
  password: str
  hosts_allow: str
