name: portaineragent
version: 1.0.16
slug: portaineragent
description: Enable portainer-agent
url: https://github.com/pabloalcantara/hassio-addons/portainer-agent

startup: once
boot: manual
init: false
startup: application

docker_api: true
hassio_api: true

options: 
  agent_secret: xxxxxxxx
  log_level: INFO
  
schema:
  agent_secret: password
  log_level: list(INFO|DEBUG)

arch:
- aarch64
- amd64
- armhf
- armv7
- i386

ports:
  9001/tcp: 9001
ports_description:
  9001/tcp: Portainer Agent Port
