name: portaineragent
version: 1.0.9
slug: portaineragent
description: Enable portainer-agent
url: https://github.com/pabloalcantara/hassio-addons/portainer-agent

startup: once
boot: manual
init: false
startup: application

docker_api: true
hassio_api: true
panel_icon: mdi:docker

options: 
  AGENT_SECRET: da9s7dhasfy82g3kDe
  AGENT_SECRET_TIMEOUT: 72h
  AGENT_CLUSTER_PROBE_TIMEOUT: 500ms
  LOG_LEVEL: INFO
  LOG_MODE: PRETTY
  EDGE: 0
  EDGE_KEY: EDGE_KEY
  EDGE_INACTIVITY_TIMEOUT: 5m
  EDGE_INSECURE_POLL: 0
  
schema:
  AGENT_SECRET: str 
  AGENT_SECRET_TIMEOUT: str
  AGENT_CLUSTER_PROBE_TIMEOUT: str
  LOG_LEVEL: str
  LOG_MODE: srt
  EDGE: str
  EDGE_KEY: str
  EDGE_INACTIVITY_TIMEOUT: str
  EDGE_INSECURE_POLL: str

arch:
- aarch64
- amd64
- armhf
- armv7
- i386

#host_network: true
ports:
  9001/tcp: 9001
  80/tcp: null
ports_description:
  9001/tcp: Portainer Agent Port
  80/tcp: Portainer Edge Port
