name: portaineragent
version: 1.0.9
slug: portaineragent
description: Enable portainer-agent
url: https://github.com/pabloalcantara/hassio-addons/portainer-agent

startup: once
boot: manual
init: false
startup: application

docker_api: true
hassio_api: true
panel_icon: mdi:docker

options: 
  AGENT_SECRET: aaaaaaaaa
  
schema:
  AGENT_SECRET: str 

arch:
- aarch64
- amd64
- armhf
- armv7
- i386

ports:
  9001/tcp: 9001
ports_description:
  9001/tcp: Portainer Agent Port
