name: portaineragent
version: 1.0.11
slug: portaineragent
description: Enable portainer-agent
url: https://github.com/pabloalcantara/hassio-addons/portainer-agent

startup: once
boot: manual
init: false
startup: application

docker_api: true
hassio_api: true

options: 
  agent_secret: xxxxxxxx
  agent_secret_timeout: 72h  
  log_level: INFO
  log_mode: PRETTY
  
schema:
  agent_secret: str 
  agent_secret_timeout: str
  log_level: str
  log_mode: str

arch:
- aarch64
- amd64
- armhf
- armv7
- i386

ports:
  9001/tcp: 9001
ports_description:
  9001/tcp: Portainer Agent Port
