name: RsyncD Backups
version: 1.1.13
slug: rsync_backups
description: Enable RsyncD with module Name rsync_backups
url: https://github.com/pabloalcantara/hassio-addons/rsync_backups
startup: once
boot: manual
init: false
startup: application    
arch:
- aarch64
- amd64
- armhf
- armv7
- i386

map:
- backup:rw
options: 
  username: user
  password: password

ports:
  14678/tcp: 14678 

schema:
  username: str
  password: str
